baseURL = "https://rozzi.media/"
languageCode = "en-us"
title = "Rozzi Media Group"
theme = "navigator-hugo"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "Portfolio"
        url     = "/portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6
    
    # Footer Service Menu
    [[menu.service]]
        name    = "Graphic Design"
        url     = "/service"
        weight  = 1
    [[menu.service]]
        name    = "Web Design"
        url     = "/service"
        weight  = 2
    [[menu.service]]
        name    = "Web Development"
        url     = "/service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "Partners"
        url     = "/about"
        weight  = 1
    [[menu.quicklink]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.quicklink]]
        name    = "FAQ's"
        url     = "/about"
        weight  = 3
    [[menu.quicklink]]
        name    = "Badges"
        url     = "/about"
        weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    footerDescription = "Rozzi Media Group is a boutique media and consulting firm that specializes in interactive websites & media experiences."

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "We deliver amazing experiences"
        description = "Rozzi Media Group is creating interactive websites & media experiences that inform the public and assist journalists, legal & real estate professionals in shining a light on the activities of state & local government agencies."
        button  = true
        btnText = "Work with us"
        btnURL  = "http://localhost:1313/contact/"
        videoThumb = "images/slider/video2.JPG"
        videoURL   = "https://www.youtube.com/watch?v=S1VlqYI82Dg"

    # About 2 Section
    [params.aboutSm]
        enable  = true
        title   = "Our work is making an impact, around New Jersey and around the world."
        description = "Rozzi Media Group's online platforms are offering tranpsarency solutions and driving local news stories that keeps the public informed & helps citizens demand better from their state & local governments."

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= "We would love to hear from you."
        address = "PO Box 32 Lanoka Harbor, NJ 08734"
        phone   = "(732)-504-3636"
        fax     = "(609)-312-7187"
        facebook= "https://www.facebook.com/gavinrozzi"
        twitter = "https://twitter.com/gavroz"
        linkedin= "https://linkedin.com/in/gavin-rozzi-077b0745"
        dribbble= ""
        instagram= ""
        mapLatitude = ""
        mapLongitude= ""
        mapMarker   = "images/marker.png"
