# Page settings
baseurl = "rozzimedia.netlify.com"
title = "Rozzi Media Group"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Gavin Rozzi"
  description = "Rozzi Media Group is a boutique media and consulting firm serving New Jersey."
  email = "hello@rozzi.media"
  # Navigation
  [params.navigation]
    brand = "Rozzi Media Group"
    home = "Home"
    work = "What We Do"
    testimonials = "Testimonials"
    services = "Services"
    about = "Who We Are"
    contact = "Contact Us"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "We are Rozzi Media"
    subtitle = 'A boutique media and consulting firm based out of southern New Jersey. Our web properties serve the public with up-to-date news & authoritative information on New Jersey government. We also provide creative, client-centered solutions including technology and media consulting, copy editing, website design.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Political Journalism"
    description = "Ocean County Politics has made an impact by publishing our online political newsletter."
    url = "https://politicsoc.com/"
    button = "Read More"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Freedom of Information"
    description = "OPRAmachine.com has released thousands of pages of government documents."
    url = "https://opramachine.com/"
    button = "Learn more"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Consulting"
    description = "Put our expertise in media and technology to work for your next project."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Our Media Properties"
    description = "See what we've created."
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Ocean County Politics"
      title = "Ocean County Politics"
      subtitle = "Ocean County's online news & opinion website - https://politicsoc.com"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "JerseyLeaks"
      title = "JerseyLeaks"
      subtitle = "Public corruption whistleblowing platform - https://jerseyleaks.org"

    [[params.work.row]]
      img = "work_3.jpeg"
      alt = "OPRAmachine"
      title = "OPRAmachine"
      subtitle = "Statewide tool for obtaining public records - https://opramachine.com"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "What We Do"

    [[params.services.item]]
      title = "WordPress / Website Design and Consulting"
      description = "We are available to provide assitance with web projects. We can also reccomend setups as far as hosting and content management systems / server tasks."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Technology Consulting"
      description = "We provide consultations to educate inviduals and groups about how to make the best use of their technology assets."
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video Production"
      description = "We have professional camera equipment and can document your event."
      icon = "icon-video2"

      [[params.services.item]]
      title = "Coming Soon: Aerial Photography"
      description = "Pending our obtaining a license from the FAA, we will soon offer drone-based aerial photography."
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Gavin Rozzi"
      position = "President / CEO"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Gavin Rozzi"
      social = [
        ["icon-twitter", "https://twitter.com/gavroz"],
        ["icon-facebook", "https://www.facebook.com/gavinrozzi"],
        ["icon-linkedin", "https://www.linkedin.com/in/gavin-rozzi-077b0745"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Monthly users of our sites"
      icon = "icon-people"
      from = 0
      to = 10000
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "We look forward to speaking with you about your inquiry."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "PO Box 32, <br> Lanoka Harbor, New Jersey 08734"],
        ["icon-phone", "(732)-504-3636"],
        ["icon-envelope", "hello@rozzi.media"],
        ["icon-globe", '<a href="https://rozzi.media/" target="_blank">rozzi.media</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Rozzi Media Group and Gavin C. Rozzi. All Rights Reserved.</a>'
